@echo off

cd c:\Development\Robot\DotCom

call robot -d ALM\TestResults\HomePage\Chat\004_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleDisplayonHomePage_Res Tests\HomePage\Chat\004_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleDisplayonHomePage_Res.robot