@echo off

cd c:\Development\Robot\DotCom

call robot -d ALM\TestResults\HomePage\Chat\006_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleDisplayonMobileAppPage Tests\HomePage\Chat\006_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleDisplayonMobileAppPage.robot