@echo off

cd c:\Development\Robot\DotCom

call robot -d ALM\TestResults\HomePage\Chat\008_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleFunctionalityonMobileAppPage Tests\HomePage\Chat\008_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleFunctionalityonMobileAppPage.robot