@echo off

cd c:\Development\Robot\DotCom

call robot -d ALM\TestResults\HomePage\Chat\003_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleDisplayonHomePage_Enterprise Tests\HomePage\Chat\003_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleDisplayonHomePage_Enterprise.robot