@echo off

cd c:\Development\Robot\DotCom

call robot -d ALM\TestResults\HomePage\Chat\007_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleFunctionalityonHomePage Tests\HomePage\Chat\007_CC_.COM_NSS_Res_Multi-Language_OnlineAndMobile_LanguageToggleFunctionalityonHomePage.robot